//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTapHoa.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHDB
    {

        public int ID { get; set; }
        public int MaHD { get; set; }
        public int MaSP { get; set; }
        public Nullable<int> GiaBan { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> ThanhTien { get; set; }
    }
}
