//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTapHoa.DTO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class HoaDonBan
    {
        [DisplayName("Mã hóa đơn")]
        public int MaHD { get; set; }
        [DisplayName("Ngày bán")]
        public string NgayBan { get; set; }
        [DisplayName("Tên khách")]
        public string TenKhach { get; set; }
        [DisplayName("SĐT")]
        public string SDT { get; set; }
        [DisplayName("Địa chỉ")]
        public string DiaChi { get; set; }
        [DisplayName("Mã nhân viên")]
        public int MaNV { get; set; }
        [DisplayName("Tổng tiền")]
        public Nullable<int> TongTien { get; set; }
    }
}
