//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTapHoa.DTO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class NhanVien
    {
        [DisplayName("Mã nhân vien")]
        public int MaNV { get; set; }
        [DisplayName("Tên nhân viên")]
        public string TenNV { get; set; }
        [DisplayName("SĐT")]
        public string SDT { get; set; }
        [DisplayName("Địa chỉ")]
        public string DiaChi { get; set; }
    }
}
