//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTapHoa.DTO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class SanPham
    {
        [DisplayName("Mã sản phẩm")]
        public int MaSP { get; set; }
        [DisplayName("Tên sản phẩm")]
        public string TenSP { get; set; }
        [DisplayName("Mã loại")]
        public int MaLoai { get; set; }
        [DisplayName("Ngày sản xuất")]
        public string NgaySX { get; set; }
        [DisplayName("Hạn sử dụng")]
        public string HanSD { get; set; }
        [DisplayName("Số lượng")]
        public Nullable<int> SoLo { get; set; }
        [DisplayName("Giá bán")]
        public Nullable<int> DonGia { get; set; }
    }
}
